### PR TITLE
Add multi hypotheses tracking ILP library for new tracking pipeline

### PR DESCRIPTION
**Pull request by chaubold**
In the new pipeline, there are two separate C++ dependencies for the ILP solver (`multiHypothesesTracking`) and the flow-based solver (`dpct`). We had the recipes for dpct already, this PR adds the recipe for `multiHypothesesTracking`. 

It can be built with gurobi or cplex support, similar to `nifty`. Then, on the ilastik side, we would for instance import (and use) the two as follows:

``` python
try:
    import multiHypoTracking_with_cplex as mht
except ImportError:
    try:
        import multiHypoTracking_with_gurobi as mht
    except ImportError:
        mht = None

import dpct

...

if solver=='ILP' and mht is not None:
    result = mht.track(model, weights)
else:
    result = dpct.trackFlowBased(model, weights)
```

Precompiled packages for linux (Ubuntu 14.04) and OSX available in my `chaubold` conda channel.

### CODE REVIEW

**Comment by stuarteberg** [comment]
This PR looks fine, but I wonder if maybe we should move these changes to different repos.  IMHO, it's better to keep the conda recipe files within each library's own repo.  That way you can update source code and build script changes in the same repo.  It also makes it easier to automatically update the version ([example](https://github.com/DerThorsten/nifty/blob/master/conda-recipe/meta.yaml#L18-L25)).

So... what do you think, @chaubold?  Are you willing to relocate these conda recipes to their respective repos?
- https://github.com/chaubold/dpct
- https://github.com/chaubold/multiHypothesesTracking
- https://github.com/chaubold/hytra

**Comment by chaubold** [comment]
Sure, I can do that!

**Comment by chaubold** [comment]
Okay, I have moved the conda recipes to the 3 respective repositories, and added the package versioning scheme that depends on the git tag as in your example. With that I was just able to rebuild all 3 packages on OSX without problems, and (because nothing else changed) the linux builds should work fine, too.

We can close this PR now, but you should probably integrate building these 3 new packages in your ilastik build VM, so we can merge https://github.com/ilastik/ilastik/pull/1363.

**Comment by stuarteberg** [comment]
Excellent, will do.  Thanks.

**Pull request closed without merging**
